### ISSUE TITLE
mmcv installation problem

### ISSUE THREAD

**Issue by AllenPu** [amazon-research/video-contrastive-learning#6]
Hi
    when I run pip install mmcv-full==1.2.7 and I found that I got the error gcc: error: unrecognized command line option ‘-std=c++14’
    error: command 'gcc' failed with exit status 1, is that because the gcc version I used is not right? My gcc version is 4.8.5

**Comment by KuangHaofei** [comment]
Hi,

I think the problem is caused by the update of the mmcv. You can refer to the official document of the installation of the mmcv: 

https://github.com/open-mmlab/mmcv#installation

For me, my cuda version is 11.2, and the pytorch version is 1.7.1. So, the below command works for me:
```shell
pip install mmcv-full==1.2.7 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html
```

Maybe you can try it, or read the document to get a suitable command for your setup. 

Let's see what happens.

**Comment by AllenPu** [comment]
Thanks for replying, that really helps!!!!
I have fixed the problem, but one other problem occurred that when I run the script that extract frames from k400, some of the .mp4 files shows decode failed~ is that because the frames are over than 300 frames would not be well decoded?
